version: '2.3'

services:
    mendixapp:
        image: bedrijf/project:v1.0
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 15s
            retries: 2
            start_period: 10s
            timeout: 3s
        environment:
            - ADMIN_PASSWORD=Password1!
            - DATABASE_ENDPOINT=postgres://mendix:mendix@db:5432/mendix
        ports:
            - 8080:80
            - 8090:81
        links:
            - db
        restart: always

    db:
        image: postgres
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 10
            start_period: 10s
            timeout: 2s
        environment:
            - POSTGRES_USER=mendix
            - POSTGRES_PASSWORD=mendix
