mendixapp:
    image: mendix/mendix-buildpack:v1
    environment:
        - ADMIN_PASSWORD=Password1!
        - DATABASE_ENDPOINT=postgres://mendix:mendix@db:5432/mendix
    ports:
        - 8080:8080
        - 8090:8081
    links:
        - db

db:
    image: postgres
    environment:
        - POSTGRES_USER=mendix
        - POSTGRES_PASSWORD=mendix
